- gramjs_generator/generators/errors.js
This fixes the issue with importing rpcbaseerrors on linux, since paths are case sensitive
> Fixed RPCBaseErrors import

- .gitignore
- __tests__/crypto/AES.spec.js
- __tests__/crypto/calcKey.spec.js
- __tests__/crypto/factorizator.spec.js
- __tests__/crypto/readBuffer.spec.js
- __tests__/extensions/HTML.spec.js
- __tests__/extensions/Markdown.spec.js
- __tests__/extensions/Scanner.spec.js
- gramjs/Utils.js
- gramjs/extensions/HTML.js
- gramjs/extensions/Markdown.js
- gramjs/extensions/Scanner.js
- gramjs/extensions/index.js
- jest.config.js
- package-lock.json
Added the `HTMLParser` class without needing to import an external library! Works similarly to the `MarkdownParser`, but allows for nested tags. `extensions/index.js` now exports `markdown` and `html` objects which both serve to wrap the parsers into easy to use `parse` and `unparse` methods.
> Add HTMLParser

- gramjs/network/connection/TCPAbridged.js
The problem appears when sending a message, because "+" is used when Buffer.concat() is needed
> Fix '\u0000\u0000' with Buffer.concat

- examples/simpleLogin.js
There was an error in the example code which was not allowing users to be able to get the sample code up and running, mainly because the `gramjs` variable contained `sessions` and not `session`. 
I have updated the code to reflect this.
We have also discussed this in #45 with @painor.
> Updated the typo in the example code to correctly call the gramjs.sessions object

- package.json
- webpack.config.js
Hi, I'm new here trying use gramjs to create a webpage telegram applications.
While I face the following error when I run `npx webpack` because of the version conflict.
```=sh
> npx webpack
assets by path ../dist/tl/ 14.1 KiB
assets by path ../dist/tl/custom/*.ts 10.6 KiB 11 assets
assets by path ../dist/tl/core/*.ts 1.99 KiB 5 assets
assets by path ../dist/tl/*.ts 1.48 KiB 4 assets
assets by path ../dist/client/*.ts 13.1 KiB 16 assets
assets by path ../dist/network/ 18.4 KiB
assets by path ../dist/network/*.ts 14.5 KiB 6 assets
assets by path ../dist/network/connection/*.ts 3.92 KiB 5 assets
assets by path ../dist/extensions/*.ts 6.52 KiB 9 assets
assets by path ../dist/crypto/*.ts 4.34 KiB 8 assets
assets by path ../dist/*.ts 11.1 KiB 7 assets
assets by path ../dist/sessions/*.ts 6.18 …
```
> Fix webpack error.

- gramjs/client/downloads.ts
Related to the issue #117 
Basically it will check if the instance is ```Api.PhotoSizeProgressive```.
If it does, it will pass ```Math.max(....size.sizes)``` to the ```fileSize``` property.
If it does not, it will use ```size.size```.
> handle the size if instanceof PhotoSizeProgressive

- gramjs/client/auth.ts
I am getting the following errors when I do not provide a password to the TelegramClient when authenticating as a user:
```
src/lib/telegram.ts:78:22 - error TS2345: Argument of type '{ phoneNumber: string; phoneCode: () => Promise<string>; onError: (err: Error) => void; }' is not assignable to parameter of type 'UserAuthParams | BotAuthParams'.
Property 'password' is missing in type '{ phoneNumber: string; phoneCode: () => Promise<string>; onError: (err: Error) => void; }' but required in type 'UserAuthParams'.
```
Below is my code:
```typescript
const client = new TelegramClient(stringSession, creds.apiId, creds.apiHash, { connectionRetries: 2 });
await client.start({
phoneNumber: creds.phone,
phoneCode: async () => authCode(),
onError: (err) => handleConnectionErr(err),
});
```
Per …
> Make password optional in UserAuthParams

- gramjs/client/TelegramClient.ts
Fix for missing method in TelegramClient.
```
TypeError: client._getInputDialog is not a function
at getInputFromResolve (/.../node_modules/telegram/tl/api.js:125:33)
at VirtualClass.resolve (/.../node_modules/telegram/tl/api.js:468:49)
at Object.invoke (/.../node_modules/telegram/client/users.js:22:19)
at TelegramClient.invoke (/.../node_modules/telegram/client/TelegramClient.js:856:28)
```
Sample code to reproduce bug:     
```js
const dialogs = await tg.invoke(new Api.messages.GetPeerDialogs({
peers: [peer]
}));
```
Maybe do something similar to `_getInputNotify` as well?
> Fix for TypeError: client._getInputDialog is not a function

- README.md
I've done a big mistake previously, I had confused `development` with `production`. The current command in the README has no difference with `npx webpack`, and its generated bundle will be working very slow because of the `eval` usage. This PR fixes it.
> Correct bundle generation command

- examples/simpleLogin.html
- examples/simpleLogin.js
- webpack.config.js
- Get `mode` from env or go with `development`.
- Set `output.library` to `telegram` to match with package name in npm.
- Remove `output.auxiliaryComment` as it is not required.
- Set `output.filename` to `telegram.js` for better readability.
> Improve Webpack configuration

- gramjs/Utils.ts
- gramjs/client/TelegramClient.ts
- gramjs/client/messages.ts
- gramjs/tl/custom/message.ts
Made some changes to editMessage function:
- Edit message method now support media.
- Update docs of `client.editMessage`. `InputBotInlineMessageID` is not supported yet so I added a warning there, I haven't tested but by looking at Telethon code it seems that I need to handle for it I will do it in the future.
- Add handler for when `message` property of `EditMessageParams` is of type `Api.Message`.
- Change `file` property type of `EditMessageParams` from `FileLike | Filelike[]` to `FileLike` because `Api.messages.EditMessage` only takes one media, not an array.
- Add return type of `Utils.getInputMedia` from return `any` to return `Api.TypeInputMedia`.
- `text` prop of `EditMessageParams` is now optional
- Add validation for if typeof `message` prop is `number` but `text` and file …
> refactor: editMessage method of client

- gramjs/client/TelegramClient.ts
- gramjs/client/messages.ts
- gramjs/tl/custom/message.ts
- `messages._pin` method: Move message param validate undefined before call client.getInputEntity so it doesn't make unnecessary network call.
- Add function overloads for `client.pinMessage`, `client.unpinMessage`
- Add @remarks to `client.getEntity` document
- Add `client.sendReadAcknowledge` method
- Add new interface `MarkAsReadParams`
- Add `Message.markRead convenience` method
- Add document for `client.sendReadAcknowledge`
> Add method for marks messages as read

- gramjs/client/TelegramClient.ts
- gramjs/client/dialogs.ts
- gramjs/client/telegramBaseClient.ts
- gramjs/client/users.ts
- gramjs/events/Album.ts
- gramjs/events/NewMessage.ts
- gramjs/extensions/Logger.ts
- gramjs/network/MTProtoSender.ts
- gramjs/tl/custom/message.ts
- package-lock.json
- **BREAKING CHANGE: Replace `Logger.setLevel` with `client.setLogLevel`**
- **BREAKING CHANGE: Anywhere you used string to set log level will now need to replace using `LogLevel` enum. E.g: `client.setLogLevel(LogLevel.ERROR)`**
- User can now pass in a custom logger as `baseLogger` as long as the custom logger extends `Logger`
- Create enum `LogLevel` to reduce potential typo errors
- Add `client.logger` return the baseLogger
- Add deprecated warning to `Logger.setLevel`
- Add getter to `Logger` for getting the current log level
> BREAKING CHANGES to Logger

- gramjs/Utils.ts
- gramjs/client/TelegramClient.ts
- gramjs/events/DeletedMessage.ts
- gramjs/events/EditedMessage.ts
- Add undefined type to `message` param of `getMessageId`
- Fix a typo in `EditedMessage` event docs
- Deleted message event
> Deleted message event

- gramjs/network/MTProtoSender.ts
- gramjs/network/RequestState.ts
- gramjs/sessions/StoreSession.ts
Due to a bug with iterating `Map` values, batched messages are never re-sent. This PR fixes it and also corrects a couple of errors related to type checking.
I believe this also closes #178. I reproduced the bug when signing in with a phone number that is served by another DC. When reconnecting, a client tries to send `help.GetConfig` and `MsgsAck` messages in a batch, receives a bad salt message, but never resends them because resending batches is broken (this is why the client also got stuck).
> Fix resending batched messages

- gramjs/network/MTProtoSender.ts
This PR actually fixes #334 (even though it was closed by the author) so that users won't need to employ the hacks by manually reconnecting the client.
Currently, the library handles reconnecting just fine, but only once. As we forget to set `userDisconnected` to `false` after connecting, the next fail in the `_recvLoop` function won't trigger reconnecting again:
https://github.com/gram-js/gramjs/blob/4a641ffba2dee5d059f1624f5285fc335eff358c/gramjs/network/MTProtoSender.ts#L489-L492
> Fix reconnecting the client

- .gitignore
- gramjs/client/fs-BROWSER.ts
- gramjs/client/uploads.ts
- package-lock.json
- package.json
- prepare_dist.sh
Telegram Premium introduces increased upload size to 4GB. But unfortunately most operating systems don't allow to open files (to consume it entirely into a memory) bigger that to 2GB (see https://github.com/nodejs/node/blob/15bb82b268584ad206606ffd46cc78c929c93fca/lib/internal/fs/utils.js#L130 ), so if we try to upload a big file (>2GB) via client we will get an error.
This is a quick fix I made to by pass this issue (already tested with uploading a big video files and it works great), but I'm not sure how good it's enough, how will it work in browsers, etc., so please review.
Also I made a helper script so I can build my fork and use it in my app (it was not easy to figure out things 😓 ) instead of package from NPM, but I can delete it if it's unnecessary.
P.S. Actually, not sure is it …
> Add support of 4GB files

- gramjs/tl/api.js
Bug description:
```js
import { Api } from 'telegram'
// globalPrivacySettings#bea2f424 flags:# archive_and_mute_new_noncontact_peers:flags.0?Bool = GlobalPrivacySettings;
let t1 = new Api.GlobalPrivacySettings({
archiveAndMuteNewNoncontactPeers: false
})
console.log(t1.getBytes())
// expect: <Buffer 24 f4 a2 be 01 00 00 00 37 97 79 bc>
// actual: <Buffer 24 f4 a2 be 00 00 00 00> ❌
let t2 = new Api.GlobalPrivacySettings({
flags: 1,
archiveAndMuteNewNoncontactPeers: false
})
console.log(t2.getBytes())
// expect: <Buffer 24 f4 a2 be 01 00 00 00 37 97 79 bc>
// actual: <Buffer 24 f4 a2 be 00 00 00 00> ❌
let t3 = new Api.GlobalPrivacySettings({
})
console.log(t3.getBytes())
// expect: <Buffer 24 f4 a2 be 00 00 00 00>
// actual: <Buffer 24 f4 a2 be 00 00 00 00> ✔
```
> Fix `flags.n?Bool` is incorrectly ignored

- gramjs/client/chats.ts
Currently the getParticipants client function doesn't support pagination on the supergroups.
It only allows the use of `limit` without being able to supply the cursor/next/offset argument.
This PR implements the use of `offset` argument to the function + removes the `offset > limit` check as it's desired for the pagination to work properly.
Example (to get 5 participants skipping the first 10):
```
const participants = await client.getParticipants(chatId, {
limit: 5,
offset: 10,
});
```
> add client.getParticipants pagination functionality

- gramjs/client/uploads.ts
Add optional maxBufferSize parameter in updateFile function for support upload big file with low memory overhead.
It will use maximal 2G memory for sending a big file in the current implementation, this requires a big cost for the server host fee.
> Support situations that low memory server (512MB) to send a big file (over 500MB)

- gramjs/client/downloads.ts
`bad` variable should have been calculated with modulo not division. Fixes https://github.com/gram-js/gramjs/issues/465
> Fix `GenericDownloadIter` offset bug

- gramjs/Helpers.ts
Currently, the function misbehaves if we try to read a signed big int as LE. For example, if you try reading `-0x010001` as unsigned LE, `<Buffer 00 00 ff 00>` will be returned while in fact, it should return `b'\xff\xff\xfe\xff'`. This PR fixes that.
> Fix issues with `readBufferFromBigInt` when `little=true`, `signed=true`

- gramjs/Helpers.ts
- gramjs/client/updates.ts
- gramjs/network/connection/Connection.ts
Simple app keep process running after calling `disconnect()`
```js
const { TelegramClient } = require("telegram");
const { StringSession } = require("telegram/sessions");
(async () => {
const apiId = "<api_id>";
const apiHash = "<api_hash>";
const sess = new StringSession("");
const client = new TelegramClient(sess, apiId, apiHash, {});
await client.connect();
await client.disconnect();
})();
```
> fix(connection): close underlying socket

- gramjs/extensions/BinaryWriter.ts
- Replace continuous buffer concatenation with a buffer array to reduce intermediate buffer creations.
- This approach mitigates potential memory leaks and improves performance, especially for large files.
Before fix.
After fix.
White strings – progress of download. Yelllow – memory usage.
Tested on 24mb mp4 file.
> Optimize BinaryWriter memory usage

- README.md
input library is deprecated and doesn't work for input anymore. 
here's the issue in details https://github.com/gram-js/gramjs/issues/657
> Remove deprecated "input" with "readline" from README.md

- gramjs/client/messages.ts
This bug occurred only if there was more than 1 media file in the message. This was happening because it was responding to the last media file uploaded.
Example of the bug:
After posting a message with 2 images, I expect that the comment will not link to any message, but it refer to the last uploaded media.
On the other hand, if there are only 1 or 0 media, the bug does not occur:
Using the [Telethon](https://github.com/LonamiWebs/Telethon) python client this behavior did not occur. After checking the source code I found that [Telethon takes the message from the discussion with the lowest id](https://github.com/LonamiWebs/Telethon/blob/a5c98aec50891e973b1ae4f38b8c080444aae664/telethon/client/messages.py#L622), instead [this library takes the first message from the …
> Fix bug in getCommentData that made the flag commentTo respond to the wrong message

- gramjs/client/TelegramClient.ts
- gramjs/client/chats.ts
added [kickParticipant](https://github.com/LonamiWebs/Telethon/blob/v1/telethon/client/chats.py#L1122) method
> feat: Add kickParticipant method to TelegramClient

- gramjs/client/uploads.ts
Temporary fix for upload memory usage.
> chore: Update max buffer size for file uploads to 20MB

- gramjs/sessions/StoreSession.ts
Related issue #480 
My guess the reason of the issue is that `session` key is being used by store2 internally and it leads to unintended overrides: https://github.com/nbubna/store/blob/0216588bc53505e290c537aaae2c52fa5ad47df8/src/store2.js#L272
The issue we're trying to solve is that when a user of gramjs is using the library for the first time, it's tempting to name the session folder `session`. However, doing so doesn't lead to persisting anything. The user may think the issue is related to his code or folder permissions. It's not obvious that the session name is the reason of the issue.
To solve this, I suggest forbidding the use `session` as a name and throwing an exception instead. Another option could be to prefix the session name with something like `gramjs_${sessionName}`, but I'm …
> Forbid 'session' as sessionName in StoreSession.ts (Close #480)

- gramjs/client/downloads.ts
- gramjs/define.d.ts
fix #708 
- fix: ProgressCallback type defination
- fix: update downloaded before invoke callback
> fix: download progress callback

- gramjs/client/telegramBaseClient.ts
- gramjs/extensions/PromisedNetSockets.ts
- gramjs/network/connection/TCPMTProxy.ts
To avoid possible misunderstanding of proxy usage.
For example, initial proxy interface allows non-mtproto proxy without socksType. But it's not possible to use the library with proxy without socksType. Also the library does not support HTTP proxy. 
So the changes might help to understand it.
> chore: stricter ProxyInterface

- gramjs/client/TelegramClient.ts
The examples misses a closing bracket, this PR fixes it plus some whitespace
> docs: fix and lint @example of getEntity

- gramjs/extensions/markdown.ts
When you send a message with a user account with "**" to render dark text, you get the error:
```js
TypeError: message.replace is not a function
```
convert "message" buffer to string to avoid this
> User Account bold markdown fix
